#! /bin/sh
# Reload the OpenSSH server when an interface comes up, to allow it to start
# listening on new addresses.

set -e

# Don't bother to restart sshd when lo is configured.
if [ "$IFACE" != eth0 ]; then
	exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi

[ -f /tmp/ifup.eth0 ] && exit 0
/usr/local/bin/footage_download_or_reboot

exit 0
